### ISSUE TITLE
Rendre le stand-up affichable sur plusieurs écrans en simultané

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/standup#5]
En utilisant WebSockets ?

Ping @maukoquiroga 

TODO:

- [x] Create Websocket Server #9
- [x] Create Websocket Client #9
- [x] Connect #9
- [x] Subscribe to channel #9
- [ ] On 'start': make them all start
- [ ] On 'start': make them all start in the same order
- [ ] On 'next-startup': make them all go to the next startup
- [ ] On 'next-startup': make them all go to the next startup in the same order
- [ ] Deploy

**Comment by maukoquiroga** [comment]
Je vais jeter un coup d'oeil !

**Comment by tchak** [comment]
On veut toujours cette fonctionnalité ?

* ça ajoute de la complexité au projet
* personne ne travaille dessus activement

**Comment by HelaG** [comment]
Je ne me souviens même plus pourquoi on voulait cette fonctionnalité en juin 2017 ^^

**Comment by gregoirenovel** [comment]
Si ma mémoire est bonne :

- On avait pas une grosse TV donc c'était difficile de lire de loin l'unique écran
- On voulait permettre le suivi du standup en remote

Ces deux objects ne me semblent plus d'actualité, je me permets de fermer.
